### ISSUE TITLE
virüs

### ISSUE THREAD

**Issue by shaunx777** [SneezingCactus/bonkclone#1]
Rojan softwares infectedme .-.

**Comment by kklkkj** [comment]
virüs CONFIRMED

**Comment by kklkkj** [comment]
tröjano

**Comment by SneezingCactus** [comment]
NÖT virüs
clösed

**Comment by shaunx777** [comment]
@kklkkj Квартира 12, Кенсингтон-Корт, 2 Генри Клоуз, Энфилд", EN2 9JU, (01992) 015144
